<?php

namespace CP\CocolocBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAnnonce($data){

		if ($data['place_min']== null) {
			$data['place_min']= 0;
			# code...
		}

		if ($data['Cat']== 'Peu importe') {
			$data['Cat']= null;
			# code...
		}


		if ($data['Ville'] == null && $data['Cat']== null) {

			$rawSql = 'select * from annonce where prix <= '.$data['prix_max'].' AND  nbplace BETWEEN '.$data['place_min'].' AND '.$data['place_max'].' AND nbdispo > 0 ORDER BY datepublication ' ;
		}
		elseif ($data['Ville']  == null && $data['Cat'] != null) {
			$rawSql = 'select * from annonce where categorie = '.'\''.$data['Cat'].'\''.' AND prix <= '.$data['prix_max'].' AND  nbplace BETWEEN '.$data['place_min'].' AND '.$data['place_max'].' AND nbdispo > 0 ORDER BY datepublication ' ;
		}
		elseif ($data['Ville']  != null && $data['Cat'] == null) {
				$rawSql = 'select * from annonce where ville = '.'\''.$data['Ville'].'\''.' AND prix <= '.$data['prix_max'].' AND  nbplace BETWEEN '.$data['place_min'].' AND '.$data['place_max'].' AND nbdispo > 0 ORDER BY datepublication ' ;
		}

		else{

			$rawSql = 'select * from annonce where ville = '.'\''.$data['Ville'].'\''.' OR categorie = '.'\''.$data['Cat'].'\''.' AND prix <= '.$data['prix_max'].' AND  nbplace BETWEEN '.$data['place_min'].' AND '.$data['place_max'].' AND nbdispo > 0 ORDER BY datepublication ' ;

		}



		$stmt = $this->getEntityManager()->getConnection()->prepare($rawSql);
		$stmt->execute([]);
		return $stmt->fetchAll();

	}




}
